name: voldt
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^13.2.2
  fpdart: ^1.1.1
  supabase_flutter: ^2.8.4
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Omnes
      fonts:
        - asset: assets/fonts/Omnes Black.ttf
          weight: 900
        - asset: assets/fonts/Omnes Black Italic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Omnes Bold.ttf
          weight: 700
        - asset: assets/fonts/Omnes Bold Italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Omnes ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Omnes ExtraLight Italic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Omnes Hairline.ttf
          weight: 100
        - asset: assets/fonts/Omnes Hairline Italic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Omnes Italic.ttf
          style: italic
        - asset: assets/fonts/Omnes Light.ttf
          weight: 300
        - asset: assets/fonts/Omnes Light Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Omnes Medium.ttf
          weight: 500
        - asset: assets/fonts/Omnes Medium Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Omnes Regular.ttf
        - asset: assets/fonts/Omnes SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Omnes SemiBold Italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Omnes Thin.ttf
          weight: 100
        - asset: assets/fonts/Omnes Thin Italic.ttf
          weight: 100
          style: italic

